### ISSUE TITLE
kpm -v restore does not print complete dependency graph

### ISSUE THREAD

**Issue by pranavkm** [aspnet/XRE#1025]
I've been attempting to diagnose an issue where multiple versions of System.Collections.Immutable are loaded in the application which causes the the app to fail at runtime. Unfortunately looking for System.Collections.Immutable in the verbose output doesn't quite help:

#### Truncated output
```
> kpm -v restore  | sls Immutable

Attempting to resolve dependency System.Collections.Immutable >= 1.1.33-beta
Attempting to resolve dependency System.Collections.Immutable >= 1.1.32-beta
Attempting to resolve dependency System.Collections.Immutable >= 1.1.33-beta
Attempting to resolve dependency System.Collections.Immutable >= 1.1.33-beta
Attempting to resolve dependency System.Collections.Immutable >= 1.1.32-beta
```

Unfortunately this doesn't help in diagnosing what packages result in a conflict in my tree. The verbose tree stops at the first level of dependencies which does not help with deeply nested tree of dependencies.

**Comment by davidfowl** [comment]
Can you show the output without the pipe/

**Comment by pranavkm** [comment]
This was running kpm restore on the Mvc solution which is quite massive. http://projectk-tc/viewLog.html?buildId=82412&buildTypeId=Mvc&tab=buildLog#_focus=103&state=103 has something that looks similar.

**Comment by TheDarkTrumpet** [comment]
That link isn't working for me...not sure it's going to work for anyone else either.  I tried projectk-tc.com and the rest as you had it and it still was a 404.

**Comment by ChengTian** [comment]
We have a new command, `kpm list`, which can show full dependency graph of a project. Upgrade your runtime and run `kpm list` in the project, you'll get output in the format of:
```
DependencyX ->
    ProjectA, PackageB, ... (a list of packages/projects that bring DependencyX in)
```

@davidfowl , `kpm list` makes the `kpm -v restore` graph useless. I think we can remove `kpm -v restore` graph now: #1126

**Comment by davidfowl** [comment]
Sweet! Nuke it

**Comment by davidfowl** [comment]
Does it help with this scenario? /cc @pranavkm

**Comment by pranavkm** [comment]
I'll give this a try and file bugs with kpm list if I run into any. Presumably we can also get FxCop using `kpm list` I presume?

**Comment by ChengTian** [comment]
Closing this issue since it's not valid anymore. Any further issue will be filed under the topic `kpm list`
