### ISSUE TITLE
File references in "code" node in project.json should raise an error if invalid

### ISSUE THREAD

**Issue by akoeplinger** [aspnet/XRE#1026]
Imagine this folder structure:
```
├───external
│       test.cs
│
└───src
        main.cs
        project.json
```

and this project.json:
``` json
{
    "version": "1.0.0-*",
    "code": [
        "**/*.cs",
        "../external/test.cs"
    ],
}
```

main.cs has a reference to a class defined in test.cs. If I "kpm build" this it works fine.

But when I change the path from "../external/test.cs" to something else (so that the file isn't found anymore), this results in no direct error. Instead it complains about not being able to find the class in main.cs, digging for the reason is not that straight-forward anymore, especially if you imagine an easy to miss typo, or case-sensitive file match.

Direct file references in the `code` node should raise an error in kpm build when the corresponding file can't be found, instead of silently ignoring it.

**Comment by muratg** [comment]
#1067

**Comment by StefH** [comment]
Another question : Is defining the external code files using an **array** supported?

I thought the only support was to use a **;** - separator?
```c#
{
    "code": "../path/to/somewhere.cs; ../../another/path/to/file.cs",
}
```

**Comment by davidfowl** [comment]
arrays are supported as well.

**Comment by StefH** [comment]
Hi David, in which version form the XRE is this support?

**Comment by davidfowl** [comment]
Since beta1 or so

**Comment by davidfowl** [comment]
This was fixed.

@troydai can you mark close this bug with the right tags?

**Comment by troydai** [comment]
@akoeplinger this bug is fixed. When individual file references for codes listed in `compileFiles` property is missing, exception will be raised. https://github.com/aspnet/Home/wiki/Project.json-file
