### ISSUE TITLE
No clear way for specifying, managing, and restoring KRE versions in source control 

### ISSUE THREAD

**Issue by MattGal** [aspnet/XRE#1030]
Obviously this is a greater issue now during initial development than it will be in the future, but there will inevitably be changes made in the runtime and dependent packages in the future that will mirror this.  

When I hit KRE-specific issues today, I use KVM upgrade to get the newer version of KRE that I need, then I need to select the version to run against if VS is already running, then things work fine.  However, if I am doing this in a project with shared source control, the KRE update does not happen in the same way it does for the other packages.  Git, by default, will ignore .kproj.user files -- and from their name it sounds like it should -- but forcibly adding changes to these files seems to be the only way to get others using the same repository to depend on the same KRE as me.  Once they do, they still need to use KVM (not part of VS) to acquire this package.

There needs to be some kind of way that is picked up in Source control by default that lets the project system know that a particular project demands a specific version (or, say "specific version or higher" if things stop getting removed) of the KRE package.

**Comment by davidfowl** [comment]
KVM is the way you manage versions of the KRE. We'll have MSIs as well. One thing you do bring up here that we have plans to implement, is a app/library saying what the minimum KRE version it requires to run.

**Comment by MattGal** [comment]
You're welcome to track it that way.  I view them as different as this is another user on the same identical machine where I was using it, versus someone trying to restore a solution from source control.  As long as it gets easier for the user experiencing the situation to know it has happened, I don't mind if you close this as dupe.
