### ISSUE TITLE
Improve globbing

### ISSUE THREAD

**Issue by muratg** [aspnet/XRE#1066]
/cc @davidfowl

**Comment by victorhurdugaci** [comment]
@muratg @davidfowl give more details about the issue. What is not working as good as expected?

**Comment by anurse** [comment]
I need some context on this. @lodejard, can you fill me in? I hear you have codez to do this more betterer.

**Comment by muratg** [comment]
@troydai @anurse should this be assigned to Troy?

**Comment by troydai** [comment]
I'm going to ask a question every assignees have asked ... what to improve?

**Comment by victorhurdugaci** [comment]
Just make it better :trollface:

**Comment by troydai** [comment]
Talked to @lodejard . This bug is duplicate with #1067 . I'll assign this to me and close as dup.

**Comment by troydai** [comment]
I'll close this bug and track the issue with #1067.
