### ISSUE TITLE
Servicing code doesn't read ProgramFiles location correctly

### ISSUE THREAD

**Issue by GrabYourPitchforks** [aspnet/XRE#1082]
Currently the servicing code reads the index file from the %PROGRAMFILES% environment variable.  This could result in different paths being read between 32-bit and 64-bit executables.

The correct logic should be:
- First check Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86).
- If that is null or empty, then check Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles).
- If that is null or empty, then check %HOME%.

FYI, this code is in ServicingTable.LoadIndex().

**Comment by anurse** [comment]
At the moment, the `KRE_SERVICING` variable is the first test, I assume we still want to keep that? Shall I rename it to `XRE_SERVICING` to match the rest of our renames? @Eilon @muratg ?

**Comment by anurse** [comment]
Also, it seems Environment.GetFolderPath is not available on CoreCLR ... :crying_cat_face:

**Comment by anurse** [comment]
Chatted with Levi. We should sync up with CoreCLR folks on getting GetFolderPath, but for beta3:

* Check %PROGRAMFILES(X86)%
* Then %PROGRAMFILES%
* Then %HOME%

**Comment by anurse** [comment]
And once again, we decided it was weird to ever check %HOME% since we have %KRE_SERVICING%

* Check %XRE_SERVICING%
* Check %PROGRAMFILES(X86)%
* Then %PROGRAMFILES%
