### ISSUE TITLE
Have a consistent error message when kpm list cannot find a project

### ISSUE THREAD

**Issue by Praburaj** [aspnet/XRE#1094]
For example when `kpm build` or `kpm pack` cannot find a project we print the error. 

`Unable to locate project.json.`. `kpm list` however prints a different message. 

`A project could not be found in C:\Users\testuser\Documents\GitHub\Logging\src.`

It will be convenient to have the same error printed as it is more clear.

**Comment by troydai** [comment]
Fixed.
