### ISSUE TITLE
kpm pack adds the binaries twice

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/XRE#1102]
Pack MusicStore (`kpm pack --runtime KRE-CoreCLR-amd64.1.0.0-beta3-10921`).

Look in `bin\output\approot\packages` and you should find all the dependencies
Look in `bin\output\src\MusicStore\bin\output\approot\packages` and you'll find again the packages.

The second bin folder shouldn't exist. 

The good thing is that it doesn't infinitely recurse.

cc @ChengTian

**Comment by glennc** [comment]
@victorhurdugaci Is this still the case?

**Comment by victorhurdugaci** [comment]
Yes, still repros

**Comment by troydai** [comment]
:+1:

**Comment by davidfowl** [comment]
This will be handled by the new globbung changes. Specifying a an exclude won't change the built in ones
