### ISSUE TITLE
Beta2 aspnet50 assemblies from Windows don't work on Mono

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/XRE#1105]
Recently, aspnet50 is based off of .Net 4.6. This framework version includes a new `String.Format(IFormatProvider, string, object)` overload and the `System.Array.Empty` member that are not yet available in Mono. Both are now referenced in the generated assemblies and so loading an assembly or jitting some functions on Mono throws MissingMethodExceptions.

Workaround: Use the beta2 toolchain on Mono itself with the same sourcecode. This does not emit calls to those members and the generated assemblies work.

**Comment by davidfowl** [comment]
No going back in time here. Will be fixed going forward
