### ISSUE TITLE
kpm list should list dependencies for the default framework if no frameworks are listed in project.json

### ISSUE THREAD

**Issue by Praburaj** [aspnet/XRE#1119]
If no frameworks are listed in `project.json`, doing a `kpm build` will build for the default framework `aspnet50`. `kpm list` should also list dependencies for default framework if no frameworks are listed in `project.json`. 

@troydai

**Comment by troydai** [comment]
Agree.

**Comment by troydai** [comment]
@muratg @glennc shall I take a look at this?

**Comment by muratg** [comment]
Question from triage: Should we even allow framework not being specified?  Should we throw instead?

/cc: @davidfowl @loudej

**Comment by troydai** [comment]
Discussed with @glennc about what framework to fall back when there is no framework listed. To keep inline with other command (`build` `bundle`), the fall back framework will be the KRE on the path.

**Comment by troydai** [comment]
Fixed https://github.com/aspnet/XRE/commit/8383656344e33baaafa2f0fa561ed6756745c747
