### ISSUE TITLE
The shell script produced by kpm pack doesn't properly mark klr as executable (if runtime packaged with application)

### ISSUE THREAD

**Issue by davidfowl** [aspnet/XRE#1130]
I've been playing with application bundling with ASP.NET 5 apps within shells like atom-shell. kpm pack --no-source works great, but when the runtime is packaged with the application it doesn't properly marked klr in the copied runtime as executable (maybe flags are lost on copy?).

Where's what I got trying to run jabbr after packing on osx:

```
artifacts/build/jabbr/web: line 13: /Users/dfowler/dev/git/JabbRv2/artifacts/build/jabbr/approot/packages/KRE-Mono.1.0.0-beta2/bin/klr: Permission denied
```

My workaround https://github.com/JabbR/JabbRv2/blob/dev/build.sh#L20

**Comment by Praburaj** [comment]
Do we need to set the flag for all the 3 files `klr`, `kpm` and `k` or just `klr` is sufficient? Do we expect anyone to use `kpm` and `k` from the bundle output?

**Comment by davidfowl** [comment]
Nobody should be using kpm and k in the bundle output but it doesn't hurt I guess.
