### ISSUE TITLE
"kpm bundle --no-source" should add generated packages to project.lock.json

### ISSUE THREAD

**Issue by ChengTian** [aspnet/XRE#1133]
Should be based on @lodejard 's work on lock file.

`kpm bundle --no-source` generates packages from dependency projects. When `locked` is `true` in `project.lock.json`, we should add the generated packages to `project.lock.json`, to make sure they can be picked up during dependency walking.

**Comment by davidfowl** [comment]
As part of this work we're going to need to delete the global.json dependencies logic.
