### ISSUE TITLE
Change the meanining of kpm install command

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/XRE#1135]
Today, `install` = `add` + `restore`.

Change as follows:

1. `add` becomes today's `install`
1. Add a flag to `add` to not restore if that's what you want (that's what `add` does today)
1. `install-g` becomes the new install (this command is not yet checked in)

cc @ChengTian @davidfowl @loudej

**Comment by glennc** [comment]
@victorhurdugaci This is required for `install -g` right?

**Comment by victorhurdugaci** [comment]
@davidfowl @lodejard do you still want to do this?

**Comment by lodejard** [comment]
I guess not, after all

**Comment by davidfowl** [comment]
Nope
