### ISSUE TITLE
Can't have ANIs that differ only by generic type arguments

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/XRE#1144]
Consider these two ANIs:

``` C#
[Runtime.AssemblyNeutral]
public interface ILogger { }

[Runtime.AssemblyNeutral]
public interface ILogger<T> : ILogger { }
```

Trying to build projects that consume these interface results in an error like:
```
error CS7069: Reference to type 'ILogger' claims it is defined in 'Microsoft.Framework.Logging.ILogger', but it could not be found
```

**Comment by DamianEdwards** [comment]
:smoking: :gun: https://github.com/aspnet/XRE/blob/dev/src/Microsoft.Framework.Runtime.Roslyn/AssemblyNeutral/TypeCompilationContext.cs#L36

**Comment by borgdylan** [comment]
This makes assemblies with backticks in the name like Msft.Frmk.Runtime.ILogger`1? I need to know this so my compiler support is coherent with this

**Comment by davidfowl** [comment]
Yes

**Comment by borgdylan** [comment]
Ok thanks. I will release a new support package for my compiler that is coherent with roslyn's output.
