### ISSUE TITLE
kpm cache clean

### ISSUE THREAD

**Issue by chmontgomery** [aspnet/XRE#1146]
New Feature request.

Would be nice to have a single command to clean your entire local cache (think [`npm cache clean`](https://docs.npmjs.com/cli/cache)). As a workaround, I can `kpm install --no-cache` on each dependency individually I need to update, but it would be more friendly to simply run a single command to clear the entire cache.

I first noticed this pain point when pushing new updates to a private NuGet feed and, without `--no-cache`, it took ~20 minutes for the cache to clear itself so `kpm install` would properly fetch my updated dependency.

Thoughts?

**Comment by davidfowl** [comment]
Why didn't you run kpm restore --no-cache so it did it all in one go?

**Comment by chmontgomery** [comment]
didn't know that was an option! Is there any documentation on the command's args of kpm anywhere?

**Comment by davidfowl** [comment]
kpm -?

**Comment by davidfowl** [comment]
kpm [command] -?

**Comment by chmontgomery** [comment]
ohhhh. sorry, didn't realize that was an option. My fault
