### ISSUE TITLE
 K cold start file-io items

### ISSUE THREAD

**Issue by jhawk42** [aspnet/XRE#1151]
@davidfowl here is the list of K cold start file io items

- Probe for the *.sha512 file over the network as well and that would not be found.
- Probe for *.nuspec over the network
- Probe for project.json files over the network
- Bunch of folder enumeration over the network
- Bunch of enumeration in the inner folder as well
- Contents of local files from d:\KCache are being read multiple times.
- File I/O Operations vs File I/O Bytes – graph - Notice that we spend a bunch of time (about 9 seconds) probing directory/file before we actually really start loading files
- File Summary – table - Something is doing a bunch of probing in \Program Files (x86)\Reference Assemblies\

**Comment by davidfowl** [comment]
Marking this initial set of items as done.
