### ISSUE TITLE
kpm simplify (Remove transitive dependencies)

### ISSUE THREAD

**Issue by bricelam** [aspnet/XRE#1159]
Stretch goal: remove any dependencies that aren't actually used at compile time.

**Comment by davidfowl** [comment]
No, this is way too hard, talk to @glennc  :smile:

**Comment by bricelam** [comment]
Isn't `kpm list` most of the way there?

**Comment by victorhurdugaci** [comment]
See this PR https://github.com/aspnet/XRE/pull/1154, I am purging all dependencies not used by some specific application. Something similar for simplify?

**Comment by glennc** [comment]
Are you talking about determining all packages that are depended on but not used? I'm not sure what we're talking about :)

**Comment by bricelam** [comment]
Sorry, I'm asking for two things at once. The first is determining which explicit (listed in project.json) dependencies are already brought in by your other dependencies and are thus redundant. The second is just a pipe dream of being able to determine which explicit dependencies are never actually used.

**Comment by glennc** [comment]
To do the first you need to take into account all the rules of the dependency walker. EF might be pulled in by a dependency, but is it the same version that the dependency resolver would've picked if you removed it from the apps dependency list? You need to remove the app level one, and then run the dependency walker to see if it changes the result.

Then when you do that you try to generalize that you end up realizing that, in the MVC solution for example, no individual top level package is required. So you end up needing to evaluate all combinations of packages and finding the smallest list. Which is expensive.

**Comment by glennc** [comment]
One thing I also tried out was running the dependency walker and drawing the nodes, showing which ones were eclipsed by packages nearer to the app. I made it so that if you highlighted a node it would show you all the packages with the same name, so you could see what was eclipsed and remove anything that was.

Do you think this would give you what you want?

**Comment by bricelam** [comment]
Ah, I forgot NuGet had that strategy for reconciling dependency versions. I saw the feature in Paket and found it very useful, but it probably works well there because they always use the newest semantically-compatible version of dependencies.

`kpm list` is probably good enough given the complexities. Drawing the dependency graph would be a great power tool to have. This feature request was just a nice-to-have in my mind. I'll let you guys decide what the best course of action is.

**Comment by muratg** [comment]
Closing this one based on Brice's last comment.
