### ISSUE TITLE
Remove package created by kpm bundle --no-source

### ISSUE THREAD

**Issue by davidfowl** [aspnet/XRE#1183]
Today when we `kpm bundle --no-source`, we end up with a nupkg in `bin/{Configuration}`. We should nuke this after extracting it to the target.

**Comment by muratg** [comment]
Assigning to @BrennanConroy.   /cc: @ChengTian for CRs later.

**Comment by BrennanConroy** [comment]
Should we nuke any pre-existing nupkg that are also in that directory? Like the ones left from a successful build.

**Comment by ChengTian** [comment]
@BrennanConroy , you need to tag an issue as `Done` after you finish it. We will generate release notes based on tags :smile:

**Comment by BrennanConroy** [comment]
Done
