### ISSUE TITLE
kpm list doesn't work for portable targets

### ISSUE THREAD

**Issue by bricelam** [aspnet/XRE#1191]
Given a `project.json` like the following.
```JSON
{
    "frameworks": {
        "net45+win8": { }
    }
}
```
I cannot get `kpm list` to work for that framework--neither with nor without the `--framework` parameter.

**Comment by Praburaj** [comment]
Dupe of https://github.com/aspnet/XRE/issues/1093?

**Comment by bricelam** [comment]
No, it didn't nullref. It just didn't show them.

**Comment by Praburaj** [comment]
I see. It might not be a dup then.

**Comment by troydai** [comment]
@bricelam `net45+win8` is not regarded as a __supported__ framework therefore not listed in the target frameworks of a project.

**Comment by Praburaj** [comment]
@troydai Do we have information to print an `unrecognized target framework net45+win8` message in this case?

**Comment by troydai** [comment]
No. Not undoable, but the information is not directly feasible. Because the framework is filtered during project loading so the list command can't know about it (https://github.com/aspnet/XRE/blob/dev/src/Microsoft.Framework.PackageManager/List/DependencyListCommand.cs#L24)

**Comment by troydai** [comment]
Close this one as no-supported / by design. @bricelam
