### ISSUE TITLE
Multiple values for kpm switches not working

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/XRE#1193]
Any switches for kpm subcommands that allow multiple values to be used do not work.

Examples:
kpm pack --framework aspnet50 aspnetcore50
kpm build --configuration debug release

**Comment by davidfowl** [comment]
That's because you're using them incorrectly :smile: .

```
kpm pack --framework aspnet50 --framework aspnetcore50
```

**Comment by ChengTian** [comment]
Yeah, we are using this syntax to avoid ambiguity.

Think about usage of `kpm pack`: `kpm [options] [argument]`. `[argument]` is the path to project root. If we support `kpm --framework <framework1> <framework2>`, how do we know whether `<framework2>` is a name of framework, or path to project root?
