### ISSUE TITLE
'Type' does not contain a definition for 'Assembly'

### ISSUE THREAD

**Issue by trayburn** [aspnet/XRE#1229]
### Title
'Type' does not contain a definition for 'Assembly'

### Functional impact
`k run` properly executes
`kpm build` results in a compile error

### Minimal repro steps
Reference the `Assembly` property of a `Type`.
Simple repo project created for your use here: https://github.com/trayburn/kpmBuildIssue

### Expected result
Both versions should compile without error, as `Type` does indeed have an `Assembly` property.

### Actual result
```
/Users/Tim/projects/ani/ConsoleApplication/Program.cs(10,31): error CS1061: 'Type' does not contain a definition for 'Assembly' and no extension method 'Assembly' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)
/Users/Tim/projects/ani/ConsoleApplication/Program.cs(12,34): error CS1061: 'Type' does not contain a definition for 'Assembly' and no extension method 'Assembly' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)
/Users/Tim/projects/ani/ConsoleApplication/Program.cs(14,31): error CS1061: 'Type' does not contain a definition for 'Assembly' and no extension method 'Assembly' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)
/Users/Tim/projects/ani/ConsoleApplication/Program.cs(16,48): error CS1061: 'Type' does not contain a definition for 'Assembly' and no extension method 'Assembly' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)

Build failed.
    0 Warnings(s)
    4 Error(s)
```

**Comment by davidfowl** [comment]
That's not a bug. Type actually does not contain the member assembly anymore. For more information head over to github.com/dotnet/corefx. 

The alternative is to use Type.GetTypeInfo().Assembly

**Comment by roji** [comment]
Sorry if I'm misunderstanding something, but Type doesn't have the `GetTypeInfo()` either in my setup. This happens both in VS CTP6 and building cmdline (CLR 1.0.0-beta5-11446 x86). Am I missing something?

**Comment by rynowak** [comment]
@roji it's an extension method in `System.Reflection` make sure you have the `using`.

**Comment by roji** [comment]
Thanks @rynowak!
