### ISSUE TITLE
Dependent Projects with mix of "code" and .cs files included fail

### ISSUE THREAD

**Issue by MattGal** [aspnet/XRE#1264]
I have the following scenario:

1) ASP.NET VNext Console app referencing VNext Class library
2) Class library has code included in project.json file like so:

    "code": [ "../includespecial/*.cs" ],  
3) Class library defines ClassA in its C# code, ClassB is defined in the included code
4) Console app uses type ClassA

Basically what happens here is that Class A does not exist for the user.  They get the error "The name 'ClassA' does not exist in the current context".   ClassB IS accessible from the app.

If I comment out the code tag in the project.json, I can then use ClassA, but not ClassB as it's no longer included.

I should either be able to freely mix and match both "relative path include" and "part of the project folder" CS files, or I should get a pretty clear error message when I do this if it's not allowed (I sure hope it's allowed).

Noted while using CoreCLR beta3-11128.

**Comment by davidfowl** [comment]
If you override code then you need to specify the defaults, e.g. 

```JSON
{
    "code": ["**/*.cs", "../includespecial/*.cs"]
}
```
/cc @troydai is working on a change to make it so that you don't have to respecify defaults, but will let you override them when needed.

**Comment by MattGal** [comment]
Cool.  Is there also an issue to list all the files found after traversing the paths found in the code property (like in Solution Explorer)?

**Comment by davidfowl** [comment]
That would be in tfs. I'm think there is one
