### ISSUE TITLE
Have earlier lockfile enforcement

### ISSUE THREAD

**Issue by ChengTian** [aspnet/XRE#1270]
https://github.com/aspnet/XRE/commit/7207b35052b183ef8cdc19d0f79d1598d4702efc#commitcomment-9886494

**Comment by davidfowl** [comment]
It might makes sense to do this in the rewrite.

**Comment by davidfowl** [comment]
This is done right?

**Comment by ChengTian** [comment]
Done in https://github.com/aspnet/XRE/commit/682efc74c9e32dac4b9055878abef97e448a6c59

**Comment by davidfowl** [comment]
Where is the tag?

**Comment by ChengTian** [comment]
Added tag and PR reference
