### ISSUE TITLE
Add support for adding a reference to assemblies on disk

### ISSUE THREAD

**Issue by abpiskunov** [aspnet/XRE#1272]
Add support for adding a reference to custom assemblies. For example fo csproj files in Add Assembly reference dialog we can browse for some assembly and add a reference to it. What is the K story for this scenario?

**Comment by Eilon** [comment]
@sayedihashimi how much of this do we already support? I thought we had some tooling for this no?

**Comment by sayedihashimi** [comment]
@eilon we support Add Ref to a system (gac) assembly. This is for loose assemblies.

**Comment by abpiskunov** [comment]
There no tooling for this. That's why it came up. How would you do it at runtime side?

**Comment by Eilon** [comment]
Oh so this is the feature that @glennc sent the mail out for with the assemblies on disk? I'll change the bug title to say it's assemblies on disk.

**Comment by sayedihashimi** [comment]
@eilon correct

**Comment by glennc** [comment]
Duplicate. Closing in favor of https://github.com/aspnet/XRE/issues/1316
