### ISSUE TITLE
Nested folders make everything break

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/XRE#1277]
1. Create a web project
2. Copy the mvc source code **inside** the solution folder so you have something like this

```
- Solution Root
    - src 
        - Project1
    - mvc
        - src
            - MvcProject1
            - MvcProject2
```
           
3.  In the solution's `global.json` file try to reference the mvc\src folder. You can try:

```
<fullpath>Solution/src/mvc/src
or
mvc/src
```

4. Notice that VS detects that you try to use sources instead of packages (in the reference node)
5. Run and notice that nothing works

It seems that if sources are more that one folder deeper than the solution root, everything breaks.

**Comment by davidfowl** [comment]
when you run what happens exactly?

**Comment by victorhurdugaci** [comment]
- If you run it complains that it cannot find the references.
- In VS it cannot resolve the types from those packages

**Comment by davidfowl** [comment]
Can you put the exception in here.

**Comment by lucamorelli** [comment]
you can find a few examples in the picture here
https://github.com/aspnet/Home/issues/334

A few samples
Error	CS0234	The type or namespace name 'Mvc' does not exist in the namespace 'Microsoft.AspNet' (are you missing an assembly reference?)	
Error	CS0246	The type or namespace name 'Authorize' could not be found (are you missing a using directive or an assembly reference?)	
Error	CS0246	The type or namespace name 'Controller' could not be found (are you missing a using directive or an assembly reference?)	
Error	CS0246	The type or namespace name 'HttpGet' could not be found (are you missing a using directive or an assembly reference?)	
Error	CS0246	The type or namespace name 'AllowAnonymous' could not be found (are you missing a using directive or an assembly reference?)	
Error	CS0246	The type or namespace name 'IActionResult' could not be found (are you missing a using directive or an assembly reference?)	
Error	CS0103	The name 'ViewBag' does not exist in the current context	
Error	CS0103	The name 'View' does not exist in the current context	
Error	CS0246	The type or namespace name 'HttpPost' could not be found (are you missing a using directive or an assembly reference?)	
Error	CS0246	The type or namespace name 'AllowAnonymous' could not be found (are you missing a using directive or an assembly reference?)	
Error	CS0246	The type or namespace name 'ValidateAntiForgeryToken' could not be found (are you missing a using directive or an assembly reference?)	
Error	CS0246	The type or namespace name 'IActionResult' could not be found (are you missing a using directive or an assembly reference?)	
Error	CS0103	The name 'ModelState' does not exist in the current context	
Error	CS0103	The name 'ModelState' does not exist in the current context	
Error	CS0103	The name 'View' does not exist in the current context	TestMvcWithSources.ASP.NET 5.0	
Error	CS0103	The name 'View' does not exist in the current context	TestMvcWithSources.ASP.NET 5.0	
Error	CS0246	The type or namespace name 'AllowAnonymous' could not be found (are you missing a using directive or an assembly reference?)	
Error	CS0246	The type or namespace name 'HttpGet' could not be found (are you missing a using directive or an assembly reference?)	

To repro is easy:
1. create a new solution with a web starter project.
2. create a new folder inside the solution folder
3. clone a repository, in this case the mvc repository, in this folder.

**Comment by davidfowl** [comment]
So this bug report isn't very accurate. So we need to formalize a repro here. 

- Seems like it doesn't have anything to do specifically with nested folders. If it does, can you reproduce this with a simple application? I couldn't.

**Comment by davidfowl** [comment]
I can reproduce the issue and it looks like it's because projects aren't added to the solution. It's a tooling issue

**Comment by victorhurdugaci** [comment]
Did you open a tooling bug?

**Comment by davidfowl** [comment]
Yes I did

**Comment by victorhurdugaci** [comment]
Thanks!

Sent from my phone
________________________________
