### ISSUE TITLE
Setting assembly/package version for ASP.NET 5 Class Library in build

### ISSUE THREAD

**Issue by Daniel15** [aspnet/XRE#1284]
When building an "ASP.NET 5 Class Library", is there a way to specify the version number as a build parameter rather than having to hardcode it in project.json? I have a project with a build server that builds NuGet packages for dev builds, and uses a version number with the date and time (like "0.1.0-dev-20140403-2203") for the NuGet package. At the moment I have a shared C# file containing the `AssemblyVersion` attributes that's automatically generated as part of the MSBuild build script, and then I include that as a link in every `csproj`.

I'd like to do the same for an ASP.NET 5 Class Library that's part of the same project, but can't figure out how to specify the version number as part of the build when doing "kpm build" or through Visual Studio. How do I make a CI box build an ASP.NET 5 Class Library and specify a custom version number to use both for the assembly and the NuGet package?

Thanks, and sorry if I'm reporting this against the wrong repository or asking in the wrong place.

**Comment by davidfowl** [comment]
Yea, don't do that anymore. Instead use the snapshot feature of project.json.

```
{
    "version": "0.1.0-dev-*"
}
```

Set the env variable K_BUILD_VERSION to something, and the * will be replaced with that variable. We're going to make this more first class so you can also set that via a flag most likely. The assembly version info will come from this as well so you should never have to set it.

**Comment by Daniel15** [comment]
Great, thanks for all your help @davidfowl! The `K_BUILD_VERSION` is the missing piece I was looking for :+1: 

With my current .NET projects I like putting the `AssemblyVersion` in a shared C# file since I can set it in one place and all projects use that version, which is handy when there's quite a few assemblies and also to ensure I don't forget to update any of them. With ASP.NET 5 Is there a way to set one version number in a central spot across a number of projects, or do I need to update it in all the package.json files every time it changes? Theoretically could the version number in package.json just be `*` and the entire version number set via `K_BUILD_VERSION`?

**Comment by davidfowl** [comment]
Thats how we build our projects. Everything is * in the project.json and no file on disk changes during build. The env variable is used to fill in the *

**Comment by Daniel15** [comment]
Awesome, thank you so much :D

**Comment by Daniel15** [comment]
@davidfowl  I get "`'*' is not a valid version string`" and "`The design time host build failed with the following error: '*' is not a valid version string`" in Visual Studio if I try setting `"version": "*"` in my project.json. Any ideas? I'm on beta3 now. Do I need to set the environment variable in Visual Studio somehow in addition to using it for command-line builds?

**Comment by davidfowl** [comment]
Can't do it for VS builds can only do it for command line builds. It only works in the pre tag at the moment:

```JSON
{
    version: "1.0.0-*"
}
```

**Comment by Daniel15** [comment]
Thanks, do you know if the Visual Studio team have plans for this?

**Comment by davidfowl** [comment]
I'll file something to make this a more first class feature.

**Comment by davidfowl** [comment]
We're the same team :smile:

**Comment by Daniel15** [comment]
Oh cool, good to know. I thought the ASP.NET team was separate from Visual Studio :+1: :+1:

**Comment by davidfowl** [comment]
It is, but the tooling for web stuff is pretty much the same team

**Comment by glennc** [comment]
@davidfowl closing this if it's filed in the tooling repo. Reopen it if you disagree.

**Comment by Costo** [comment]
In case you arrived here after some Googling like me, be aware that `K_BUILD_VERSION` is now `DNX_BUILD_VERSION` in Asp.Net Core 1.0 RC1

https://github.com/dotnet/cli/issues/571

**Comment by danielwertheim** [comment]
@davidfowl  What is the preferred way now to accomplish something like having one shared assemblyinfo having the version information when sharing that between many projects in one solution?

A pre-compile script that looks at single resource and patches the version in project.json or?

**Comment by nathan-alden-sr** [comment]
@danielwertheim I'm wondering the same thing. Now that I can't create a link to a single GlobalAssemblyInfo.cs, I'm not sure what the best way is to version the assemblies. It would've been nice if project.json handled that automatically, versioning all assemblies to whatever the NuGet package version is.

**Comment by nathan-alden-sr** [comment]
I ended up writing a PowerShell script that my CI process calls to set all the project.json `"version"` properties and a `GlobalAssemblyInfo.cs` file's version attributes. Then I include `GlobalAssemblyInfo.cs` in each `project.json` as a compile include.
