### ISSUE TITLE
"Clean" target on kproj doesn't delete NuGet packages

### ISSUE THREAD

**Issue by Daniel15** [aspnet/XRE#1301]
`msbuild blah.kproj` on an ASP.NET Class Library generates .nupkg and .symbols.nupkg files, but `msbuild blah.kproj /t:clean` does not delete these files.

**Comment by BillHiebert** [comment]
We currently don't have a clean target at all. There is an item on the backlog to fix this.

**Comment by glennc** [comment]
Closing this, the issue is tracked in the tooling repositories.

**Comment by Daniel15** [comment]
Thanks! Is there a public issue I can watch or is it only in an internal tracker?
