### ISSUE TITLE
Add Microsoft.Framework.PackageManager to nuget.org feed

### ISSUE THREAD

**Issue by giggio** [aspnet/XRE#1307]
Currently it is not there, and there is no way we can reference it. Any chance this could be made available? It would be nice to be able to reason programatically about a package dependency.

My specific scenario is: I have installed chromedriver, I want to run it, and I need to find the executable. I could read project.json, but it is not installed directly, but on another dependency. I would need to walk the dependencies to find it, but this work has been done already on Microsoft.Framework.PackageManager.

**Comment by davidfowl** [comment]
We're not going to do this. We're already working on merging NuGet and kpm. You should eventually be able to use reason about dependencies using the nuget libraries.

**Comment by davidfowl** [comment]
If you want to figure out where a package is at runtime then there's another runtime API for that.

**Comment by giggio** [comment]
Great! What API is this?

**Comment by davidfowl** [comment]
ILibraryManager: https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/KestrelEngine.cs#L17
