### ISSUE TITLE
When there is a P2P reference to a project that doesn't build we should get a build error

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/XRE#1323]
Consider this scenario.

MyWebProject (ASP.NET 5 web project) references MySharedProject (ASP.NET 5 class library). If there is a compile error in MySharedProject when you execute ```kpm biuld``` on ```MyWebProject``` we should get a build error that ```MySharedProject``` doesn't build. Instead we get ``build succeeded```.

cc @davidfowl @danroth27 @glennc @BillHiebert @barrytang

**Comment by davidfowl** [comment]
Dupe of  https://github.com/aspnet/XRE/issues/583
