### ISSUE TITLE
*.sh requires bash at /bin/bash

### ISSUE THREAD

**Issue by lefb766** [aspnet/XRE#1341]
*.sh specify `/bin/bash` as the path where bash resides. However, there can be systems don't have bash located at /bin/bash, so we can't run k nor kpm run on such systems.

### Problem factors
* Bash location could be /bin, /usr/local/bin or wherever.
* Some Linux systems (e.g. Debian-based ones) may not have bash installed.
* *sh includes some bash-specific code which can be avoided.

This issue may relate to: #1064 aspnet/Home#346

### Possible solution
Port *.sh to run on dash, changing the shebangs into `#! /bin/sh`. Dash is a shell that aims to be POSIX-compliant, so it is safer to assume /bin/sh on every system could run the script written for dash.

I found some .cs codes also refer to bash, so this solution may involve changes to them.

**Comment by davidfowl** [comment]
Moved to https://github.com/aspnet/Universe/issues/172
