### ISSUE TITLE
Issues when consuming Assembly neutral interfaces in the IDE

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/XRE#171]
When consuming assembly neutral interfaces see errors like the following
 
The type 'Microsoft.Framework.Runtime.IAssemblyLoaderEngine' exists in both 'Microsoft.Framework.Runtime.Interfaces.kproj, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'Microsoft.Framework.Runtime.IAssemblyLoaderEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
 
                There can also be other cascading errors due to this – typically type conversions like Cannot convert from ‘blah’ to ‘IFoo’
                
                Repro:  Occurs when Project1 is referencing Project2 and Project2 defines an assembly neutral interface consumed by Project 1. Ie
                Project1
                                SomeFile.cs – has reference to IFoo
                                Project.json – Includes Project2 in its list of references
                Project2
                                IFoo.cs
                
                Why this occurs
Project1’s intellisense engine sets up a project reference to Project2, and it gets a generated assembly containing the assembly neutral interface IFoo.  The intellisense project see’s the same interface defined twice and raises the error. 
 
Possible Solutions
 1 Change the DesignTimeHost to not return these generated assemblies for interfaces defined in project dependencies
 2 Have the DesignTimeHost pass additional metadata reference about where it came from. VS would use this information in deciding whether to pass the reference to the intellisense project or not.
 3 The assembly neutral assembly data includes the originating type. VS could search its project references to see if that already exists and ignore it.

**Comment by muratg** [comment]
ANI's are no more :/
