### ISSUE TITLE
Circular reference with Testing

### ISSUE THREAD

**Issue by bricelam** [aspnet/XRE#358]
This repo uses Xunit.KRunner from Testing. Testing uses Microsoft.Framework.Runtime.Interfaces.

**Comment by glennc** [comment]
@bricelam Is this still an issue?

**Comment by bricelam** [comment]
Yep, with xunit.runner.aspnet from aspnet.xunit now. I suppose we could move XRE's tests into another repository. The CI workflow would be:
1. Build XRE
2. Build aspnet.xunit
3. Test XRE
4. Cascade, rinse & repeat

**Comment by davidfowl** [comment]
We're not fixing this. We don't look at the test folder for repo dependencies. I'm sure this problem exists for other repos too

**Comment by muratg** [comment]
Closing per last comment
