### ISSUE TITLE
'kpm pack' should accept --packages parameter

### ISSUE THREAD

**Issue by troydai** [aspnet/XRE#448]
Commit https://github.com/aspnet/Helios/commit/af1607ef946b1c6f17b49cb66ae47ccdc597378a break performance run because the KRE_PACKAGES is not set on perf CI. As a result the ASPNET.LOADER.DLL is not packed into performance app.

`kpm pack` relies on `KRE_PACKAGES` to search for packages. As a result the environment variable become a hard requirement. I believe `kpm pack` should be asymmetric to `kpm restore` so that you can fully rely on command line manipulation to accomplish a build.

**Comment by muratg** [comment]
@troydai closing this. If there's still an issue around bundle, please reactivate
