### ISSUE TITLE
kpm bundle --overwrite does not remove extra packages in output folder under approot

### ISSUE THREAD

**Issue by balachir** [aspnet/XRE#471]
Build WTE 10723

1. New Empty Web application
2. Add 'Microsoft.AspNet.Mvc' package to project.json
3. Save and build
4. Open cmd prompt and navigate to the application folder
5. Run following cmd (this is the command that tooling uses during Publish):

C:\Users\balach\Documents\Visual Studio 14\Projects\EmptyWebApp2\EmptyWebApp2>"C
:\Users\balach\.kre\packages\kre-svr50-x86.1.0.0-alpha3-10163\bin\kpm.cmd" pack
--runtime "C:\Users\balach\.kre\packages\kre-svr50-x86.1.0.0-alpha3-10163" --out
 "C:\PublishOut\EmptyWebApp2\Kpack1" --appfolder wwwroot --overwrite

6. Check the output folder, all the packages are there under approot

![image](https://cloud.githubusercontent.com/assets/8246794/3690004/082c8422-1345-11e4-945d-da90c0dc3234.png)

7. Remove 'Microsoft.AspNet.Mvc' package from project.json and hit save
8. Run same kpm pack command as above, and check the output folder again

ACTUAL
Mvc packages are still there

EXPECTED
Mvc packages should be removed because I specified the --overwrite option

**Comment by glennc** [comment]
Duplicate: https://github.com/aspnet/XRE/issues/714
