### ISSUE TITLE
kpm pack should not overwrite AspNet.Loader.dll 

### ISSUE THREAD

**Issue by balachir** [aspnet/XRE#475]
1. New empty web application EmptyApp5

2. Add 'Microsoft.AspNet.StaticFiles' package to project.json, add a Default.html page and add 'app.UseFileServer()' to Startup.cs. Ctrl-F5 > works

3. Open command prompt - run kpm pack
![image](https://cloud.githubusercontent.com/assets/8246794/3709559/7f8fa322-1459-11e4-8354-cc9f312e1284.png)

4. Get the files and timestamps of the kpm pack output
![image](https://cloud.githubusercontent.com/assets/8246794/3709560/8b738ffa-1459-11e4-85b9-4a00462085ec.png)

5. Make a change to Default.html and Startup.cs. Ctrl-F5 > works

6. Run kpm pack again
![image](https://cloud.githubusercontent.com/assets/8246794/3709593/91f024e6-145a-11e4-8619-143123cbd997.png)

7. Get the files and timestamps of the kpm pack output
![image](https://cloud.githubusercontent.com/assets/8246794/3709594/a049856e-145a-11e4-90b3-511542369629.png)

8. Run windiff on the 2 output files

ACTUAL

1. For AspNet.Loader.dll under wwwroot\bin, timestamp is different
![image](https://cloud.githubusercontent.com/assets/8246794/3709607/348f3de0-145b-11e4-9b0e-c18545eaf916.png)

2. For all the packages under approot, timestamp is different
![image](https://cloud.githubusercontent.com/assets/8246794/3709608/4b7791f6-145b-11e4-8742-338909ad26ed.png)

EXPECTED
Timestamps not to change for either case above

**Comment by glennc** [comment]
I think this is by design. The overwrite command is designed to take overwrite any files that exist in the destination and the application being packed. It doesn't diff things and only overwrite if changes are made. Feel free to disagree and re-open.
