### ISSUE TITLE
Make KRuntime understand new package layout

### ISSUE THREAD

**Issue by ChengTian** [aspnet/XRE#521]
@lodejard  is adding configuration subfolders for packages. The new layout contains `PackageName\Version\Debug` folder and `PackageName\Version\Release` folder. We should make `KRuntime` (`kpm pack`, dll look-up algorithm and etc.) understand the new layout.

**Comment by ChengTian** [comment]
@davidfowl I think this issue is not valid anymore. Should I close it?

**Comment by muratg** [comment]
@ChengTian @davidfowl closing this.... repoen if more work is needed here
