### ISSUE TITLE
Investigate global packages ala npm install -g

### ISSUE THREAD

**Issue by davidfowl** [aspnet/XRE#540]
It'd be really nice to deliver an end to end command line building/publising/consuming experience for vNext.

You're building a command line application e.g. aspnet-scaffolder:

- Run `kpm pack` (I think we'll need a way to package applications as well)
- Publish it to NuGet.org 
- Anybody can consume it via `kpm install aspnet-scaffolding -g`
- aspnet-scaffolding is now available on the command line

This also runs cross platform

**Comment by victorhurdugaci** [comment]
Done https://github.com/aspnet/XRE/pull/1154

**Comment by tugberkugurlu** [comment]
Is this in? I was expecting to see `-g` switch for `install` command but I cannot :disappointed: 

> Z:\>kpm help install
> Usage: kpm install [arguments] [options]
> 
> Arguments:
>   [name]     Name of the dependency to add
>   [version]  Version of the dependency to add, default is the latest version.
>   [project]  Path to project, default is current directory
> 
> Options:
>   -s|--source <FEED>          A list of packages sources to use for this command
> 
>   -f|--fallbacksource <FEED>  A list of packages sources to use as a fallback
>   -p|--proxy <ADDRESS>        The HTTP proxy to use when retrieving packages
>   --no-cache                  Do not use local cache
>   --packages                  Path to restore packages
>   --ignore-failed-sources     Ignore failed remote sources if there are local pa
> ckages meeting version requirements
>   --quiet                     Do not show output such as HTTP request/cache info
> rmation
>   -?|-h|--help                Show help information
> 
> Z:\>

I am on kpm version 1.0.0-beta4-11117.

**Comment by victorhurdugaci** [comment]
Use `kpm commands`

Sent from my phone
________________________________

**Comment by tugberkugurlu** [comment]
Is there a sample for this feature somewhere or doc? I made `kpm commands install <package-name>` work but I am assuming it doesn't behave as I expected :disappointed:

**Comment by victorhurdugaci** [comment]
Sorry, there are no samples yet.

What package are you trying to install and what are you expecting to happen?

Sent from my phone
________________________________

**Comment by tugberkugurlu** [comment]
@victorhurdugaci I am trying to install **xunit.runner.kre** package. It installs but I cannot use it globally from the command line buy running xunit.runner.kre.

I am expecting for the library I installed available globally for me to use (if it's a console application). For example, when I run `npm install azure -g`, `azure` command is available for me globally.

Did I understand the behavior of this feature wrong?

**Comment by victorhurdugaci** [comment]
If you try to install `xunit.runner.kre` you'll get the following error

   The specified package is not an application. The package was added but no commands were installed.

Here is how the commands work. In project.json you can specify commands. When you pack such an application, we are generating scripts for those commands. If you run `kpm commands install` on a package with commands, it will add the commands on the path.

`xunit.runner.kre` cannot be globally installed because it doesn't expose any commands.

**Comment by victorhurdugaci** [comment]
I create a bug against xunit to provide the commands required for global install https://github.com/xunit/aspnet.xunit/issues/14

**Comment by tugberkugurlu** [comment]
@victorhurdugaci Thanks! 

OK, I created a project with a command and packed it. It looks like this:

![image](https://cloud.githubusercontent.com/assets/328122/6351626/f8040d60-bc34-11e4-878e-c7a057846309.png)

I ran the `kpm commands install` as below:

![image](https://cloud.githubusercontent.com/assets/328122/6351573/9183a438-bc34-11e4-95b1-a55c81881215.png)

I still don't have `k-http` under my path. I tried this on kpm version 1.0.0-beta4-11117.

**Comment by tugberkugurlu** [comment]
I guess I figured it out. It strangely installs the script under `C:\Users\tugberk.ugurlu\bin` instead of `C:\Users\tugberk.ugurlu\.kre\bin`. I am assuming it should be `C:\Users\tugberk.ugurlu\.kre\bin` because it is what I have inside `$env:PATH`.

**Comment by victorhurdugaci** [comment]
I was able to repro your issue. I'm taking a look
