### ISSUE TITLE
kpm pack to provide a switch to pack the current KRE

### ISSUE THREAD

**Issue by Praburaj** [aspnet/XRE#694]
Currently to pack a runtime while `kpm pack` we need to provide the KRE information that needs to be packed. It will be convenient to provide a special case like below which will pack the current KRE under which kpm is running. 

```
kpm pack --runtime current
```

**Comment by victorhurdugaci** [comment]
@glennc can we do this for rc1, please? Deployment for automation is complicated without it...

**Comment by troydai** [comment]
it will be nice to support kvm alias as well.
