### ISSUE TITLE
kpm pack is deleting files in wwwroot even though overwrite flag is not set

### ISSUE THREAD

**Issue by naianacampos** [aspnet/XRE#713]
1. Create empty vNext WAP
2. Add a html file under wwwroot
3. from cmd line, kpm pack --out c:\temp
4. delete the html file under wwwroot
5. repeat step 3

 [Observed]
html file is no longer in wwwroot

 [Expected]
the file should only be deleted if the --overwrite flag is set

**Comment by glennc** [comment]
We are removing overwrite. See: https://github.com/aspnet/XRE/issues/1227
