### ISSUE TITLE
kpm bundle --overwrite is not deleting output folder

### ISSUE THREAD

**Issue by naianacampos** [aspnet/XRE#714]
WTE 10/7
1. Create empty vNext WAP
2. from cmd line, kpm pack --out c:\temp 
3. in project.json, delete dependencies in CodeGenerator
4. from cmd line, kpm pack --out c:\temp --overwrite

[Observed]
the code generator packages can still be found in c:\temp even though the overwrite flag was set 

[Expected]
the overwrite flag should 'Remove existing files in target folders'

**Comment by glennc** [comment]
We are removing overwrite. See: https://github.com/aspnet/XRE/issues/1227
