### ISSUE TITLE
kpm pack --overwrite mismatch with stated behavior

### ISSUE THREAD

**Issue by ardalis** [aspnet/XRE#856]
`kpm pack --overwrite` says "Remove existing files in target folders."

"overwrite" implies that new files will overwrite existing files with the same names, if necessary.  It doesn't imply wiping out everything in the destination and then replacing it.  An existing term for the latter behavior is "clean" such as Visual Studio uses today.

Recommendation (choose one):
1) Rename `--overwrite` to something else, like `--clean`.
or
2) Change the behavior and help text to state "Overwrite existing files in target folders." (do not delete or touch files in target folders that are not being overwritten)

**Comment by glennc** [comment]
We are removing overwrite. See: https://github.com/aspnet/XRE/issues/1227
