### ISSUE TITLE
Terminal colors not restored on dependency fetch failure

### ISSUE THREAD

**Issue by djrenren** [aspnet/XRE#897]
On running `kpm restore` if a dependency is not found, the dark-green color that kpm uses, persists after the command finishes.

(My default terminal text color is light green. see how it gets stuck as dark green)
![capture](https://cloud.githubusercontent.com/assets/634666/5050131/8c9ec78a-6bf9-11e4-92e9-dca097d5e6f3.PNG)

**Comment by glennc** [comment]
close as duplicate
