### ISSUE TITLE
ANIs and cross-platform libraries

### ISSUE THREAD

**Issue by bricelam** [aspnet/XRE#960]
After a very thorough investigation of Entity Framework's use of Assembly-Neutral Interfaces in a cross-platform library, I've come to the conclusion that we need to do one of three things.

1. Cut them
2. Strong-name them
3. Don't do tear-out on non-ASP.NET frameworks (i.e. treat them as normal interfaces in the containing assembly) and issue a warning that they won't work there

See also #633, aspnet/EntityFramework#779 & aspnet/EntityFramework#999

**Comment by Eilon** [comment]
@muratg @glennc can we close this bug too?

**Comment by davidfowl** [comment]
RIP
