### ISSUE TITLE
Improve project.json schema to allow host service skip restoring some packages

### ISSUE THREAD

**Issue by troydai** [aspnet/XRE#991]
Host service like Kudu make leverage project.json to restore packages remotely. However some dependencies in the project.json may be only useful in development environment. For that case restoring those packages is a waste. 

The current project.json scheme doesn't imply what dependencies are development only. Therefore the host service won't be able to decide whether to skip restoring a package.

**Comment by ChengTian** [comment]
Here is an example marking a dependency as dev component: https://github.com/aspnet/Signing/blob/abe67b657b1d0306976d9ddbe77136f9ab5a82a8/src/Microsoft.Framework.Signing/project.json#L4

**Comment by muratg** [comment]
Looks like this is doable.  Closing this one.
